openapi: 3.0.0
info:
  title: Mobile Specs API
  description: API for fetching mobile phone brands and specifications
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/mobile-specs
    description: Local development server

paths:
  /brands:
    get:
      tags:
        - Brands
      summary: Get all mobile phone brands
      description: Returns a list of all mobile phone brands.
      responses:
        '200':
          description: A list of mobile phone brands
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BrandDTO'

  /phone-specs/{customId}:
    get:
      tags:
        - PhoneSpecs
      summary: Get phone specifications by custom ID
      description: Returns detailed specifications for a mobile phone by its custom ID.
      parameters:
        - name: customId
          in: path
          required: true
          description: The custom ID of the phone
          schema:
            type: integer
      responses:
        '200':
          description: Detailed specifications of the phone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneSpecsResponseDTO'

components:
  schemas:
    BrandDTO:
      type: object
      properties:
        brandValue:
          type: string
          description: The name of the mobile phone brand
          example: "Samsung"

    PhoneSpecsResponseDTO:
      type: object
      properties:
        phoneDetails:
          $ref: '#/components/schemas/PhoneDetailsDTO'
        gsmNetworkDetails:
          $ref: '#/components/schemas/GsmNetworkDetailsDTO'
        gsmLaunchDetails:
          $ref: '#/components/schemas/GsmLaunchDetailsDTO'
        gsmBodyDetails:
          $ref: '#/components/schemas/GsmBodyDetailsDTO'
        gsmDisplayDetails:
          $ref: '#/components/schemas/GsmDisplayDetailsDTO'
        gsmPlatformDetails:
          $ref: '#/components/schemas/GsmPlatformDetailsDTO'
        gsmMemoryDetails:
          $ref: '#/components/schemas/GsmMemoryDetailsDTO'
        gsmCameraDetails:
          $ref: '#/components/schemas/GsmCameraDetailsDTO'
        gsmSoundDetails:
          $ref: '#/components/schemas/GsmSoundDetailsDTO'
        gsmCommunicationsDetails:
          $ref: '#/components/schemas/GsmCommunicationsDetailsDTO'
        gsmFeaturesDetails:
          $ref: '#/components/schemas/GsmFeaturesDetailsDTO'
        gsmBatteryDetails:
          $ref: '#/components/schemas/GsmBatteryDetailsDTO'
        gsmMiscDetails:
          $ref: '#/components/schemas/GsmMiscDetailsDTO'
        gsmTestsDetails:
          $ref: '#/components/schemas/GsmTestsDetailsDTO'

    PhoneDetailsDTO:
      type: object
      properties:
        customId:
          type: integer
          example: 103693
        yearValue:
          type: string
          example: "2022"
        brandValue:
          type: string
          example: "Samsung"
        modelValue:
          type: string
          example: "Galaxy S22 Ultra 5G"

    GsmNetworkDetailsDTO:
      type: object
      properties:
        networkTechnology:
          type: string
          example: "GSM / CDMA / HSPA / EVDO / LTE / 5G"
        network2GBands:
          type: string
          example: "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2"
        network3GBands:
          type: string
          example: "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100"
        network4GBands:
          type: string
          example: "1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 32, 38, 39, 40, 41, 66"
        network5GBands:
          type: string
          example: "1, 2, 3, 5, 7, 8, 12, 20, 25, 28, 38, 40, 41, 66, 75, 77, 78 SA/NSA/Sub6"
        networkSpeed:
          type: string
          example: "HSPA 42.2/5.76 Mbps, LTE-A (7CA) Cat20 2000/200 Mbps, 5G (5+ Gbps DL)"

    GsmLaunchDetailsDTO:
      type: object
      properties:
        launchAnnounced:
          type: string
          example: "2022, February 09"
        launchStatus:
          type: string
          example: "Available. Released 2022, February 25"

    GsmBodyDetailsDTO:
      type: object
      properties:
        bodyDimensions:
          type: string
          example: "163.3 x 77.9 x 8.9 mm (6.43 x 3.07 x 0.35 in)"
        bodyWeight:
          type: string
          example: "228 g / 229 g (mmWave) (8.04 oz)"
        bodySim:
          type: string
          example: "Nano-SIM and eSIM or Dual SIM (2 Nano-SIMs and eSIM, dual stand-by)"
        bodyBuild:
          type: string
          example: "Glass front (Gorilla Glass Victus+), glass back (Gorilla Glass Victus+), aluminum frame"
        bodyOther1:
          type: string
          example: "IP68 dust/water resistant (up to 1.5m for 30 mins)"
        bodyOther2:
          type: string
          example: "Armor aluminum frame with tougher drop and scratch resistance (advertised)"
        bodyOther3:
          type: string
          example: "Stylus, 2.8ms latency (Bluetooth integration, accelerometer, gyro)"

    GsmDisplayDetailsDTO:
      type: object
      properties:
        displayType:
          type: string
          example: "Dynamic AMOLED 2X, 120Hz, HDR10+, 1750 nits (peak)"
        displaySize:
          type: string
          example: "6.8 inches, 114.7 cm2 (~90.2% screen-to-body ratio)"
        displayResolution:
          type: string
          example: "1440 x 3088 pixels (~500 ppi density)"
        displayProtection:
          type: string
          example: "Corning Gorilla Glass Victus+"
        displayOther1:
          type: string
          example: "Always-On display"

    GsmPlatformDetailsDTO:
      type: object
      properties:
        platformChipset:
          type: string
          example: "Exynos 2200 (4 nm) - Europe"
        platformCpu:
          type: string
          example: "Octa-core (1x2.8 GHz Cortex-X2 & 3x2.50 GHz Cortex-A710 & 4x1.8 GHz Cortex-A510) - Europe"
        platformGpu:
          type: string
          example: "Xclipse 920 - Europe"
        platformOs:
          type: string
          example: "Android 12, upgradable to Android 13, One UI 5"

    GsmMemoryDetailsDTO:
      type: object
      properties:
        memoryCardSlot:
          type: string
          example: "No"
        memoryInternal:
          type: string
          example: "128GB 8GB RAM, 256GB 12GB RAM, 512GB 12GB RAM, 1TB 12GB RAM"
        memoryOther1:
          type: string
          example: "UFS 3.1"

    GsmCameraDetailsDTO:
      type: object
      properties:
        mainCameraFeatures:
          type: string
          example: "LED flash, Auto-HDR, panorama"
        mainCameraQuad:
          type: string
          example: "108 MP"
        mainCameraVideo:
          type: string
          example: "8K@24fps, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, stereo sound rec., gyro-EIS"
        selfieCameraFeatures:
          type: string
          example: "Dual video call, Auto-HDR"
        selfieCameraSingle:
          type: string
          example: "40 MP"
        selfieCameraVideo:
          type: string
          example: "4K@30/60fps, 1080p@30fps"

    GsmSoundDetailsDTO:
      type: object
      properties:
        sound35MmJack:
          type: string
          example: "No"
        soundLoudspeaker:
          type: string
          example: "Yes, with stereo speakers"
        soundOther1:
          type: string
          example: "32-bit/384kHz audio"
        soundOther2:
          type: string
          example: "Tuned by AKG"

    GsmCommunicationsDetailsDTO:
      type: object
      properties:
        communicationsBluetooth:
          type: string
          example: "5.2, A2DP, LE"
        communicationsNfc:
          type: string
          example: "Yes"
        communicationsPositioning:
          type: string
          example: "GPS, GLONASS, BDS, GALILEO"
        communicationsRadio:
          type: string
          example: "No"
        communicationsUsb:
          type: string
          example: "USB Type-C 3.2, OTG"
        communicationsWlan:
          type: string
          example: "Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct"

    GsmFeaturesDetailsDTO:
      type: object
      properties:
        featuresOther1:
          type: string
          example: "Samsung DeX, Samsung Wireless DeX (desktop experience support)"
        featuresOther2:
          type: string
          example: "Bixby natural language commands and dictation"
        featuresOther3:
          type: string
          example: "Samsung Pay (Visa, MasterCard certified)"
        featuresOther4:
          type: string
          example: "Ultra Wideband (UWB) support"

    GsmBatteryDetailsDTO:
      type: object
      properties:
        batteryCharging:
          type: string
          example: "45W wired, PD3.0"
        batteryType:
          type: string
          example: "Li-Ion 5000 mAh, non-removable"

    GsmMiscDetailsDTO:
      type: object
      properties:
        miscColors:
          type: string
          example: "Phantom Black, White, Burgundy, Green, Graphite, Red, Sky Blue, Bora Purple"
        miscModels:
          type: string
          example: "SM-S908B, SM-S908B/DS, SM-S908U, SM-S908U1, SM-S908W, SM-S908N, SM-S9080, SM-S908E, SM-S908E/DS"
        miscPrice:
          type: string
          example: "€983.59 / $708.99 / £833.00 / C$1,049.00 / ₹93,500"
        miscSar:
          type: string
          example: "1.18 W/kg (head) 0.98 W/kg (body)"
        miscSarEu:
          type: string
          example: "1.05 W/kg (head) 1.58 W/kg (body)"

    GsmTestsDetailsDTO:
      type: object
      properties:
        testsBatteryLife:
          type: string
          example: "Endurance rating 108h"
        testsCamera:
          type: string
          example: "Photo / Video"
        testsDisplay:
          type: string
          example: "Contrast ratio: Infinite (nominal)"
        testsLoudspeaker:
          type: string
          example: "-27.3 LUFS (Good)"
        testsPerformance:
          type: string
          example: "AnTuTu: 968359 (v9)"